sudo: required
language: ruby
rvm:
- 2.3.7
node_js:
- '7'
env:
  global:
    - TRAVIS_BRANCH=${TRAVIS_BRANCH} # define for usage in projects bash scripts
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
branches:
  only:
  - master
  - develop
before_install:
- openssl aes-256-cbc -K $encrypted_79b548fb7a17_key -iv $encrypted_79b548fb7a17_iv -in cloud.tar.enc -out cloud.tar -d
- tar xvf cloud.tar
- sudo apt-get install -y nodejs npm
- npm i
- npm i -g html-minifier
- npm i -g webpack
- npm i -g webpack-cli
- npm i -g @babel/core
- npm i -g babel-loader
- npm i -g eslint
- npm i -g eslint-config-prettier
- npm i -g prettier
- gem install html-proofer
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    gcloud version || true
    if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
    echo "LOAD SOURCE"
    source /home/travis/google-cloud-sdk/path.bash.inc
    gcloud version
    gcloud auth activate-service-account --key-file key.$TRAVIS_BRANCH.json
  fi
before_script:
  - chmod +x ./script/cibuild
script:
- set -e
- npm run prettier
- npm run eslint
# Run the build and html-proofer
- ./script/cibuild
# minify all html
- html-minifier --input-dir ./_site --output-dir ./_site --collapse-whitespace --file-ext
  html
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    if [ $TRAVIS_BRANCH = "master" ]; then
      # set project
      gcloud config set project $PROJECTPROD
      # set website details for the correct bucket
      # gsutil web set -m index.html -e 404.html gs://$BUCKET
      # empty bucket (website stays alive on the CDN)
      gsutil -m rm -r gs://$BUCKET/**
      # cd into website dir
      cd _site
      # Upload data to bucket
      gsutil -m cp -r ./ gs://$BUCKET
      # upload videos with gzip
      gsutil -m -h "Cache-Control:public,max-age=900" cp ./assets/header.mp4 gs://$BUCKET/assets/header.mp4
      gsutil -m -h "Cache-Control:public,max-age=900" cp ./assets/header.webm gs://$BUCKET/assets/header.webm
      # Allow viewing of files (for website purposes)
      # gsutil iam ch allUsers:objectViewer gs://$BUCKET
      # Invalidate the CDN
      gcloud compute url-maps invalidate-cdn-cache semi-technology --host www.semi.technology --path "/*" --async
      gcloud compute url-maps invalidate-cdn-cache semi-network --host www.semi.network --path "/*" --async
    fi
  fi
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    if [ $TRAVIS_BRANCH = "develop" ]; then
      # set project
      gcloud config set project $PROJECTDEV
      # set website details for the correct bucket
      gsutil web set -m index.html -e 404.html gs://$BUCKETDEV
      # empty bucket (website stays alive on the CDN)
      gsutil -m rm -r gs://$BUCKETDEV/**
      # cd into website dir
      cd _site
      # Upload data to bucket, GZIP (-Z) and set Cache Control for CDN
      gsutil -m -h "Cache-Control:public,max-age=900" cp -Z -r ./ gs://$BUCKETDEV
      # upload videos with gzip
      gsutil -m -h "Cache-Control:public,max-age=900" cp ./assets/header.mp4 gs://$BUCKETDEV/assets/header.mp4
      gsutil -m -h "Cache-Control:public,max-age=900" cp ./assets/header.webm gs://$BUCKETDEV/assets/header.webm
      # Allow viewing of files (for website purposes)
      gsutil iam ch allUsers:objectViewer gs://$BUCKETDEV
    fi
  fi
notifications:
  slack:
    secure: DOpQAFFKSgONCUnAfdo9lkny4iyagwRbCl5KaV6sF8FU292LQkPncLdhD5lb7LjafKUxZricNBDTQXZxN2BxdgTprVbQPuiuMjn13WGS96ecHnzLL8lsGMk04WTG5OElytgRFwcaRvr/rS2rickmR6WQ8IRjCCBUNdKnMKFvaInCB5UjtADDhS/HWKysHl+4dA//LIJwibbnThl8peCO/45AboLMyJb0BwTAyzozpDQOj0NiPUsB4l+7ly7D3gffXqZHFwcbUcSHRVq1EDihhhITjDgF6k/3HkWH3xBt2ArAh5t4FwK0R0bacsrWNr7OlpoGju0Oefx1/9zEnqSwa5A5Q2UgGH3CdS1IZtSFNiDqN+E0LqKeckfZVwWGhLFRniEW/3GaUx+AuV+1jcEzxb2CHO9P8PTki6OycTidef3YwPxV9eH7rqtF3aEBN5DfoJbLE05AGKswmMKR1FDa1dShhrYisWTytvL+bWBKmzLcYUtY+PFgUghaotLXyNbWFSl9yTqJYBg2R8U7YR3cbbitTIBwXyLDH7fk/eZPlavTL/Dmdlyo7VviQEQ4c04QjLvPstwGLsJKVsrSN74uZy0g+DEnLA0yAT4pKQMFs9jv8YOZ1U8XWRGScqhqm1E8thal4sCblDqjMgWQTXuQ8U2nem1J5inhJXtswdnM324=
