weaviate_version: 0.8.6
markdown: kramdown
kramdown:  
    parse_block_html: false
rdiscount extensions: [smart]
sass:
    style: compressed # opposed to "expanded"
    sass_dir: css/_sass
exclude:
    - "*.json"
    - "Gemfile*"
    - "*.enc"
    - vendor
    - README.md
    - "*.draft"
plugins:
    - jekyll-autoprefixer
autoprefixer:
    browsers:
        - last 5 versions
url: "https://www.semi.network"