weaviate_version: 0.8.6
topic_order:
    - _
    - Learn
    - Start
    - Implement
url: "https://www.semi.network"
auto: true
markdown: kramdown
kramdown:  
    parse_block_html: false
rdiscount extensions: [smart]
sass:
    style: compressed # opposed to "expanded"
    sass_dir: css/_sass
exclude:
    - "*.json"
    - "Gemfile*"
    - "*.txt"
    - "*.enc"
    - vendor
    - README.md
    - "grid.html"
#    - "styleguide.html"
    - "styletiles.html"
plugins:
    - jekyll-autoprefixer
    - jekyll-sitemap
autoprefixer:
    browsers:
        - last 2 versions